### ISSUE TITLE
模板集变量未正常显示

### ISSUE THREAD

**Issue by ifooth** [Tencent/bk-bcs-saas#1000]
![image](https://user-images.githubusercontent.com/1853121/121490222-669bcb00-ca07-11eb-9690-734734937e1c.png)

**Comment by jamesgetx** [comment]
这里提一个bug: 模板集表单模式，导入yaml后，因为使用了变量，但是变量不存在，然后删除变量一直提示如下错误
![image](https://user-images.githubusercontent.com/7370814/121987352-e8567480-cdca-11eb-9a72-3edf023f0066.png)
