### ISSUE TITLE
PR支持单元测试——与流水线集成

### ISSUE THREAD

**Issue by jamesgetx** [Tencent/bk-bcs-saas#1004]
单元测试与流水线集成，同时考虑支持多集群版本的测试(涉及到集群资源的模块，能够支持1.16，1.14等多版本)。
多版本步骤参考：
- 测试环境搭建不同版本的集群
- 通过环境变量同时指定待测试的模块
- 集成到流水线中

**Comment by ifooth** [comment]
对集群环境依赖的单元测试，可以参考cmdb，使用内部流水线跑单元测试
https://github.com/Tencent/bk-cmdb/pull/5209/checks?check_run_id=2791870892

**Comment by schneesu** [comment]
已经支持 1.21 版本集群单元测试，部分未通过的单元测试调试中

**Comment by jamesgetx** [comment]
@schneesu 流程中，也考虑对多版本进行测试验证

**Comment by schneesu** [comment]
基础版本已实现，未通过的单元测试已修复（不含标准日志的3个），后续需求拆解到单独issue：Saas多版本（https://github.com/Tencent/bk-bcs-saas/issues/1214），多版本集群（https://github.com/Tencent/bk-bcs-saas/issues/1216）
