### ISSUE TITLE
资源详情yaml/json支持过滤数据

### ISSUE THREAD

**Issue by dellkeji** [Tencent/bk-bcs-saas#1005]
资源的yaml/json相对固定，因此，希望可以支持到过滤字段，比如过滤replica、containers等，过滤到后，可以到指定字段所在位置，如果有多个，可以切换

包含两个地方
- 资源视图页面
- 应用下的to yaml

**Comment by HubuHito** [comment]
https://github.com/Tencent/bk-bcs-saas/pull/1025 提交已经合并
