### ISSUE TITLE
helm命令行参数开放

### ISSUE THREAD

**Issue by dellkeji** [Tencent/bk-bcs-saas#1090]
牵涉到两部分

1. 前端部分功能的重新设计

这里有个问题需要讨论： 支持的参数是让用户自己填写，还是转换为勾选框或输入框，比如

--force=true， 

- ![image](https://user-images.githubusercontent.com/4350885/123571105-1e98e880-d7fc-11eb-8b5b-7f01a4ca499c.png)

- ![image](https://user-images.githubusercontent.com/4350885/123571438-c8787500-d7fc-11eb-8415-e8a102820f33.png)

![image](https://user-images.githubusercontent.com/4350885/123570458-d0cfb080-d7fa-11eb-9ab0-d6876c359ff0.png)

2. 后端功能的处理

2.1 helm操作相关的处理
2.2 允许开放命令行

**Comment by dellkeji** [comment]
确认时，可以提示执行的helm命令

**Comment by asapsonter** [comment]
awesome work

**Comment by dellkeji** [comment]
#1105
