### ISSUE TITLE
资源视图优化

### ISSUE THREAD

**Issue by HubuHito** [Tencent/bk-bcs-saas#1091]
1. 图表配置优化
![image](https://user-images.githubusercontent.com/17620291/123572233-6b7dbe80-d7fe-11eb-9849-8edcfdfc197c.png)

2. 表格宽度优化
![image](https://user-images.githubusercontent.com/17620291/123572207-5d2fa280-d7fe-11eb-90a7-4002233a7c78.png)

**Comment by jamesgetx** [comment]
网络性能指标缺少区分网络入或者出流量
