### ISSUE TITLE
节点管理页面最小宽度调整

### ISSUE THREAD

**Issue by dellkeji** [Tencent/bk-bcs-saas#1157]
# 描述

当浏览器缩小时，会导致问题部分功能覆盖

![image](https://user-images.githubusercontent.com/4350885/124697350-31f13580-df19-11eb-8a8d-1abb9525e04a.png)

**Comment by HubuHito** [comment]
1. 新界面尽量用flex布局
2. 老界面统一检查下 1366 * 768 分辨率下的异常
