### ISSUE TITLE
Watch with too old resourceVersion raise 410 exception

### ISSUE THREAD

**Issue by schneesu** [Tencent/bk-bcs-saas#1203]
### 出现场景
用户长时间位于列表页，前端长时间使用同一个 resourceVersion 执行 subscibe，一段时间后会出现该情况

### 推荐修复方案
1. 订阅接口在捕获 410 异常后，刷新返回的 resourceVersion，前端使用新的 resourceVersion 进行轮询
2. 订阅接口捕获 410 异常后，抛出指定错误码，前端重新进行一次 list 操作，之后按原逻辑 watch

### 错误堆栈
<img width="1280" alt="wecom-temp-3c2aadb2f55ebc650a820fd18ba66ad3" src="https://user-images.githubusercontent.com/37054728/125716344-2ccb15b3-40f9-4d3c-8802-c6fa3f38aa59.png">

**Comment by jamesgetx** [comment]
讨论后，按照方案2处理
