### ISSUE TITLE
feature: 资源视图优化 0708

### ISSUE THREAD

**Issue by schneesu** [Tencent/bk-bcs-saas#1225]
- [x] 【重要】资源 ToYaml 展示页面需要添加 “复制代码” 按钮
- [ ] 【建议】ToYaml 样式保持一致，一般 apiVersion - kind - metadata - xxx
- [ ] 【重要】若选中命名空间，进入详情页退出/更新/删除后，请保留选中的命名空间
- [ ] 【建议】若填写按名称搜索，进入详情页退出/更新/删除后，请保留填写内容

**Comment by jamesgetx** [comment]
![image](https://user-images.githubusercontent.com/7370814/126329564-f971b1ee-3b4d-4ed2-8f6c-7ae43e0cf453.png)
另外，这里的”名称“列可以拖动宽度

**Comment by jamesgetx** [comment]
![image](https://user-images.githubusercontent.com/7370814/127801553-5c9cc179-396f-41f9-a127-283d4987699c.png)
名字，命名空间，镜像3列考虑可拖动宽度
