### ISSUE TITLE
feat: HPA，自定义资源优化项

### ISSUE THREAD

**Issue by schneesu** [Tencent/bk-bcs-saas#1342]
- [x] 创建 / 更新日志展示完全，可以占用编辑框位置，或设置滚动条
![image](https://user-images.githubusercontent.com/37054728/129537705-4e243539-1666-4cb8-ad9b-3beb4ed0aba6.png)

- [x] 自定义资源创建/更新，固定住 CRD
![image](https://user-images.githubusercontent.com/37054728/129537819-0e135169-91ec-41ec-ac92-4b733d710b5d.png)

**Comment by xyjunco** [comment]
这里有两个问题
1. 报错提示在文本编辑区域，不是很明显
2. 报错内容过多，用户不易查看

和设计师沟通，这里使用可配置行数的 message 框来展示报错，内容超过最多行数时会显示 「复制」按钮
组件目前已支持

<img width="1224" alt="wecom-temp-d91f69b26e3812cd2e3e2fc474f90b80" src="https://user-images.githubusercontent.com/4710858/133358838-9969e0f7-0455-4133-acdf-cc62979ead9d.png">

**Comment by schneesu** [comment]
不赞成使用 message 框的方式，这里将错误信息放到编辑区的原因是
1. 与普通的错误信息做区分，突出是配置提交触发的错误，引导用户修改配置
2. 容器服务 SaaS 目前 message 均会在一段时间后消失，不利于用户查看详细的错误信息

**Comment by xyjunco** [comment]
和设计沟通，采用编辑框内提示错误信息的方式
错误框可自由拉抻高度，可收起折叠，也可以将内容复制出来
设计稿已交付  @HubuHito
