### ISSUE TITLE
bcs_projmgr访问身份校验不通过

### ISSUE THREAD

**Issue by Jimgong826** [Tencent/bk-bcs-saas#518]
bcs_projmgr部署完成后通过paas平台访问，/user/projects/ 400报错（bkToken参数缺失）， /user/users/ 400报错（bk_token参数缺失），在cookie中有bk_token！请问这是什么原因？是需要在哪里添加token信息呢？是bk_token还是bkToken呢？有办法关闭身份校验吗？

**Comment by freyzheng** [comment]
这里验证的是cookie中的bk_token,页面发起请求的时候，F12看一下request中的cookie头部是否有带上对应的bk_token。
注意cookie的域名作用范围
