### ISSUE TITLE
如何更改前端UIUE，整合到对方公司SaaS平台，符合对方公司整改要求的建议

### ISSUE THREAD

**Issue by tianyige21** [Tencent/bk-bcs-saas#932]
### 是BUG反馈还是需求提交(Is this a BUG REPORT or FEATURE REQUEST)? (choose one):
需求提交
### BK-BCS-SaaS 版本(The versions used):
最新版本
### 发生了什么(What happened):
前端UIUE不能在你们的代码里面更改，因为涉及到你们频繁的变更，如果直接拉你们的代码到我们自己的库合代码，出错成本会变大
### 期望是什么(What you expected to happen):
你们的代码能不能有一个口子，模版我们可以直接修改，修改完能符合我们公司的UIUE规范，里面的文案也能符合
### 如何复现(How to reproduce it):
随时复闲
### 相关的日志详情和截图等(Log &  @Screenshot):
无
### 备注(Anything else we need to know):
无

**Comment by jamesgetx** [comment]
@tianyige21 你好。这里给出建议：如果只是样式的修改  可以自行加样式文件覆盖。如果涉及到产品文案、交互等修改，可以拉取分支做定制版本。后续如何合并更新代码我们没有合适的方案给到。

**Comment by tianyige21** [comment]
可以自行加样式文件覆盖你们给过类似的开发模版或者方案吗

**Comment by tianyige21** [comment]
> @tianyige21 你好。这里给出建议：如果只是样式的修改 可以自行加样式文件覆盖。如果涉及到产品文案、交互等修改，可以拉取分支做定制版本。后续如何合并更新代码我们没有合适的方案给到。

可以自行加样式文件覆盖你们给过类似的开发模版或者方案吗
